# nixpacks.toml - Configure Nixpacks for the Python backend

providers = ["python"] # Force using the Python provider

[phases.setup]
# Ensure necessary OS packages (like postgresql-client for psycopg2) are available if needed
# nixPkgs = ["...", "postgresql"] # Example: uncomment and add if needed

[phases.install]
# Command to install dependencies, relative to project root
cmds = ["pip install --upgrade pip", "pip install -r backend/requirements.txt"]

[start]
# The command to start the application, relative to project root
cmd = "gunicorn --pythonpath . backend.app:app --bind 0.0.0.0:$PORT" 